# Generated by Django 6.0.6 on 2026-07-07 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Lunes ... 6=Domingo')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('escuchador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_disponibilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloque de Disponibilidad',
                'verbose_name_plural': 'Bloques de Disponibilidad',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
