# Generated by Django 6.0.6 on 2026-07-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0003_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_url',
            field=models.TextField(blank=True, help_text='Contenido Base64 o URL de la foto de perfil', null=True),
        ),
        migrations.CreateModel(
            name='RegistroAnimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('animo', models.CharField(choices=[('genial', 'Great'), ('bien', 'Good'), ('normal', 'Okay'), ('mal', 'Down'), ('enojado', 'Angry')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_animo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ánimo',
                'verbose_name_plural': 'Registros de Ánimo',
                'ordering': ['-fecha'],
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
