# Generated by Django 6.0.6 on 2026-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0004_alter_usuario_foto_url_registroanimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reagendada', 'Rescheduled - Pending Your Approval')], default='pendiente', max_length=20),
        ),
    ]
