# Generated by Django 6.0.6 on 2026-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0005_alter_sesion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, help_text='Si el receptor ya abrió esta conversación después de recibirlo.'),
        ),
    ]
