# Generated by Django 6.0.6 on 2026-07-24 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0006_mensaje_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Brief summary shown on cards.')),
                ('full_content', models.TextField(blank=True, help_text='Full article body. Used for articles.')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('stress_management', 'Stress Management'), ('academic_success', 'Academic Success'), ('healthy_habits', 'Healthy Habits'), ('sleep', 'Sleep'), ('relationships', 'Relationships'), ('mindfulness', 'Mindfulness')], max_length=40)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('download', 'Download')], default='article', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('source_name', models.CharField(blank=True, help_text='e.g. World Health Organization', max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('additional_sources', models.TextField(blank=True, help_text='Optional extra sources, one per line: Name|https://example.com')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading/watching time in minutes.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search.', max_length=300)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube link for video resources.')),
                ('video_duration', models.CharField(blank=True, help_text='e.g. "8:24"', max_length=20)),
                ('video_channel', models.CharField(blank=True, max_length=120)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resources/pdfs/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
